extern const uint16_t EDGE;
#define COLOR TS_16b_Yellow


// :

const uint16_t columnBitmap [ 12 * 20 ] = {

EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,

};
#define COLOR TS_16b_Yellow


//  0

const uint16_t n0MBitmap [ 18 * 30 ] = {

EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,
EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,
EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,
EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,
EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,

};

//  1

const uint16_t n1MBitmap [ 18 * 30 ] = {

EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

//  2

const uint16_t n2MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

//  3

const uint16_t n3MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

//  4

const uint16_t n4MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};


//  5

const uint16_t n5MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

//  6

const uint16_t n6MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};


//  7

const uint16_t n7MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

//  8

const uint16_t n8MBitmap [ 18 * 30 ] = {

EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,
EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,
EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,
EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,
EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,

};


//  9

const uint16_t n9MBitmap [ 18 * 30 ] = {

COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,EDGE,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,
COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,COLOR,

};

